name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v2.x

      - name: Type check
        run: deno check

      - name: Lint
        run: deno lint

      - name: Format check
        run: deno fmt --check

      - name: Run tests
        run: deno task test
